
import {
  type LucideIcon,
  UserPlus,
  KeyRound,
  ShieldCheck,
  Settings,
  HelpCircle,
  CheckSquare,
  Calculator,
  Ratio,
  Zap,
  QrCode,
  Compass,
  Ruler,
  ZoomIn,
  Smartphone,
  Mic,
  NotebookText,
  ListChecks,
  Timer,
  Folder,
  FileText,
  ImagePlay,
  Video,
  Music,
  Dices,
  BookOpen,
  Languages,
  CloudSun,
  Newspaper,
  Download,
  Link,
  Shield,
  Wifi,
  BarChart2,
  Wallpaper,
  Cloudy,
  BotMessageSquare,
  TerminalSquare,
  Image,
  Blocks,
  PilcrowSquare,
  CalendarCheck,
  FileCog,
  FileSearch2,
  ScanText,
  MailPlus,
  AudioLines,
  BrainCircuit,
  Star,
  Clapperboard,
  SpellCheck,
  ShoppingCart,
  HeartPulse,
  Search,
  SmilePlus,
  BookMarked,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  UserAccountCreation: UserPlus,
  PersistentLogin: KeyRound,
  LoginVerification: ShieldCheck,
  ProfileSettings: Settings,
  ForgotPassword: HelpCircle,
  RememberMe: CheckSquare,
  Calculator: Calculator,
  UnitConverter: Ratio,
  Flashlight: Zap,
  QRBarcodeScanner: QrCode,
  Compass: Compass,
  LevelTool: Ruler, // Using ruler as a stand-in
  RulerARMeasurement: Ruler,
  MagnifyingGlass: ZoomIn,
  Mirror: Smartphone,
  VoiceRecorder: Mic,
  NotesNotepad: NotebookText,
  ToDoList: ListChecks,
  AlarmTimerStopwatch: Timer,
  FileManager: Folder,
  PDFReader: FileText,
  ImageEditor: ImagePlay,
  VideoTrimmerEditor: Video,
  AudioPlayerMixer: Music,
  RandomNumberGenerator: Dices,
  OfflineDictionaryThesaurus: BookOpen,
  Translator: Languages,
  WeatherUpdates: CloudSun,
  NewsAggregator: Newspaper,
  LinkDownloader: Download,
  QRActions: Link,
  VPNIntegration: Shield,
  WiFiAnalyzer: Wifi,
  DataUsageTracker: BarChart2,
  WallpaperRingtoneDownloader: Wallpaper,
  CloudBackupSync: Cloudy,
  AIChatAssistant: BotMessageSquare,
  AICodingScriptGenerator: TerminalSquare,
  AIImageGenerator: Image,
  AISummarizer: Blocks,
  AITranslator: Languages,
  AITextRewriter: PilcrowSquare,
  AIReminderPlanner: CalendarCheck,
  AIFileOrganizer: FileCog,
  AIPDFExtractor: FileSearch2,
  AIOCRHandwritingRecognition: ScanText,
  AIEmailDraftWriter: MailPlus,
  AIVoiceToText: AudioLines,
  AIBrainstormIdeaGenerator: BrainCircuit,
  AIPhotoEnhancer: Star,
  AIVideoSummarizer: Clapperboard,
  AIGrammarSpellChecker: SpellCheck,
  AIShoppingAssistant: ShoppingCart,
  AIHealthTips: HeartPulse,
  AISmartSearch: Search,
  AIEmotionDetector: SmilePlus,
  AIStoryGenerator: BookMarked,
  Placeholder: BrainCircuit,
};
